#define DRIVERBIN "/home/dj/Printer-Applications-Framework/share/driver"
#define DATADIR "/home/dj/Printer-Applications-Framework/share"
#define CACHEDIR "/home/dj/Printer-Applications-Framework/var/cache"
#define SERVERBIN "/home/dj/Printer-Applications-Framework/server"
#define INSTALLDIR "/home/dj/Printer-Applications-Framework/"